language: python
python:
    - "3.6.3"
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install tox-travis
    - pip install coveralls
script:
    - tox
after_success:
    coveralls
